# Default values for webapp.
# This is a YAML-formatted file.

image:
  repository: pfe2023.azurecr.io
  name: sampleapi
  tag: "57"
  pullPolicy: IfNotPresent

# -- Number of pod replicas
replicaCount: 1

# -- Environmental vars, key value pairs, e.g. `MY_VAR: 'value 123'`
env: {}
#  MY_VAR: 'value 123'

# -- Env vars from Secrets, the key is env var name, `secretName` and `secretKey` reference the Secret
secretEnv: {}
#  SECRET_THING:
#    secretName: my-secret
#    secretKey: password

# Network traffic to the pods
service:
  port: 80
  targetPort: 3000
  type: LoadBalancer

# Configure Ingress, switch on/off-able
ingress:
  # -- Use an ingress or not
  enabled: false
  # -- Set the IngressClass to use
  className:
  # -- Ingress host *must* be set if enabled
  host:
  tls:
    # -- Use TLS on ingress
    enabled: false
    # -- Secret holding cert *must* be set if TLS enabled
    secretName:
  # -- Extra annotations to set on the ingress
  annotations: {}

# Limit resources
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# -- Any secrets needed to pull image
imagePullSecrets: []
# -- Override the chart name used for this release
nameOverride: ""
# -- Override full release name, normally autogenerated
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- The name of the service account to use. If not set a name is generated
  name:
livenessProbe:
  # -- URL path checked by liveness & readiness probes
  path: /
  # -- Number of liveness probe failures to tolerate
  failureThreshold: 3
  # -- Delay before liveness probe starts
  initialDelaySeconds: 20
  # -- Interval between liveness probe checks
  periodSeconds: 20
persistence:
  # -- Use persistent volume
  enabled: false
  # -- Persistent volume size
  size: 1Gi
  # -- Persistent volume access mode
  accessMode: ReadWriteOnce
  # -- Persistent volume mount path, must be set if enabled
  mountPath:

# -- Pod security context spec
podSecurityContext: {}

# -- Security context spec
securityContext: {}

# -- Node selector spec
nodeSelector: {}

# -- Node tolerations spec
tolerations: []

# -- Node affinity spec
affinity: {}

# -- Pod annotations
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '3000'

# -- Pod labels
podLabels: {}

# -- Deployment annotations
deploymentAnnotations: {}

# -- PVC annotations
pvcAnnotations: {}
